# TensorFlow Shapes

This notebook demonstrates the most common TensorFlow operations.

In [50]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import tensorflow as tf



In [51]:
# check tensorflow installation
print(tf.__version__)

2.18.0


In [52]:
# setting some parameters
tf.random.set_seed(42)

In [53]:
# Utility functions

# a pandas table demonstrating value, type, and shape of the tensors
def display_table(tensor_list, index):   
    data = {'Value': [t.numpy() for t in tensor_list],
            'Type': [t.dtype for t in tensor_list],
            'Shape': [t.shape for t in tensor_list],
            'Rank': [tf.rank(t).numpy() for t in tensor_list]}
    
    df = pd.DataFrame(data, index=index)

    return df

In [54]:
# an integer scalar
a_int = tf.constant(2)
print(a_int)

# a float scalar
a_float = tf.constant(3.14)

# a string scalar
a_str = tf.constant("Hello, TensorFlow!")

# a pandas table demonstrating value, type, and shape of the tensors
display_table([a_int, a_float, a_str], ['a_int', 'a_float', 'a_str'])

tf.Tensor(2, shape=(), dtype=int32)


Value                Type Shape  Rank
a_int                        2    <dtype: 'int32'>    ()     0
a_float                   3.14  <dtype: 'float32'>    ()     0
a_str    b'Hello, TensorFlow!'   <dtype: 'string'>    ()     0

As observed on the table above, the rank of scalars is 0 and hence they do not have dimensions.

In [55]:
# trying to access the value of a scalar using a tensor will result in an error
# a_int[0]

# a_float[0]

In [56]:
# an integer vector
a_int_vector = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# a float vector
a_float_vector = tf.constant([3.14, 6.28, 9.42, 12.56])

# a string vector
a_str_vector = tf.constant(["Hello", "Brave", "New", "World", "of", "parallel", "computing", "with", "Tensor", "Flow"])

# a pandas table demonstrating value, type, and shape of the tensors
display_table([a_int_vector, a_float_vector, a_str_vector], ['a_int_vector', 'a_float_vector', 'a_str_vector'])

Value  \
a_int_vector                      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]   
a_float_vector                          [3.14, 6.28, 9.42, 12.56]   
a_str_vector    [b'Hello', b'Brave', b'New', b'World', b'of', ...   

                              Type Shape  Rank  
a_int_vector      <dtype: 'int32'>  (10)     1  
a_float_vector  <dtype: 'float32'>   (4)     1  
a_str_vector     <dtype: 'string'>  (10)     1

In [57]:
# trying to instantiate a tensor with different data types will result in an error
# tf.constant([1, 2, 3, 4, 'five'])

In [58]:
# accessing the value of a vector (rank-1) using an index will return the corresponding scalar (rank-0)
s = a_int_vector[0]

# vector tensors can be sliced
t = a_float_vector[1:3]

# inverting a sentence using slicing
u = a_str_vector[::-1]

display_table([s, t, u], ['a_int_vector[0]', 'a_float_vector[1:3]', 'a_str_vector[::-1]'])


Value  \
a_int_vector[0]                                                      1   
a_float_vector[1:3]                                       [6.28, 9.42]   
a_str_vector[::-1]   [b'Flow', b'Tensor', b'with', b'computing', b'...   

                                   Type Shape  Rank  
a_int_vector[0]        <dtype: 'int32'>    ()     0  
a_float_vector[1:3]  <dtype: 'float32'>   (2)     1  
a_str_vector[::-1]    <dtype: 'string'>  (10)     1

In [59]:
# let's play a little bit with matrices

# a 4x4 matrix of fibonacci numbers
fibo = tf.constant([[1, 0, 0, 0], [1, 1, 0, 0], [1, 1, 2, 0], [1, 1, 2, 3]])

# a 1x5 matrix (row vector) of prime numbers
prime = tf.constant([[2, 3, 5, 7, 11]])

# a 5x1 matrix (column vector) of odd numbers
odd = tf.constant([[1], [3], [5], [7], [9]])

display_table([fibo, prime, odd], ['fibo', 'prime', 'odd'])

Value              Type  \
fibo   [[1, 0, 0, 0], [1, 1, 0, 0], [1, 1, 2, 0], [1,...  <dtype: 'int32'>   
prime                                 [[2, 3, 5, 7, 11]]  <dtype: 'int32'>   
odd                            [[1], [3], [5], [7], [9]]  <dtype: 'int32'>   

        Shape  Rank  
fibo   (4, 4)     2  
prime  (1, 5)     2  
odd    (5, 1)     2

In [60]:
# tensors of different ranks can be sliced

# selecting a single element from a 2-rank tensor
a = fibo[0, 0]

# selecting a row from a 2-rank tensor
b = fibo[1]
b2 = fibo[1,:] # equivalent to the above

# selecting a column from a 2-rank tensor
c = fibo[:, 2]

# selecting a sub-matrix from a 2-rank tensor
d = fibo[2:, 2:]

display_table([a, b, b2, c, d], ['fibo[0, 0]', 'fibo[1]', 'fibo[1:]','fibo[:, 2]', 'fibo[2:, 2:]'])

Value              Type   Shape  Rank
fibo[0, 0]                   1  <dtype: 'int32'>      ()     0
fibo[1]           [1, 1, 0, 0]  <dtype: 'int32'>     (4)     1
fibo[1:]          [1, 1, 0, 0]  <dtype: 'int32'>     (4)     1
fibo[:, 2]        [0, 0, 2, 2]  <dtype: 'int32'>     (4)     1
fibo[2:, 2:]  [[2, 0], [2, 3]]  <dtype: 'int32'>  (2, 2)     2

The table above shows us an important detail. Whenever we slice a tensor, the result is of the lowest rank that fits the resulting tensor. This can be a problem in pipelines in which we need to keep the same dimensions along the flow.

In [61]:
# a 3-rank tensor (a cube) of random numbers
cube = tf.random.uniform([3, 3, 3], minval=0, maxval=100, dtype=tf.int32)
cube

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[87, 89, 61],
        [86, 92, 84],
        [83, 43, 71]],

       [[91, 52, 40],
        [51, 81, 20],
        [ 8, 59, 32]],

       [[ 9, 99, 11],
        [12, 97, 94],
        [19,  1, 61]]], dtype=int32)>

In [62]:
# tensors of ranks higher than 3 are supported

# a 4-rank tensor (a hypercube) of random numbers
hypercube = tf.random.uniform([2, 2, 2, 2], minval=0, maxval=100, dtype=tf.int32)
hypercube

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[98, 43],
         [19, 94]],

        [[32, 13],
         [84, 42]]],


       [[[86, 24],
         [81, 63]],

        [[46,  0],
         [69, 69]]]], dtype=int32)>

In [63]:
# a 5-rank tensor of random numbers
penta = tf.random.uniform([2, 2, 2, 2, 2], minval=0, maxval=100, dtype=tf.int32)
penta

<tf.Tensor: shape=(2, 2, 2, 2, 2), dtype=int32, numpy=
array([[[[[ 4, 92],
          [77, 24]],

         [[23,  7],
          [84, 19]]],


        [[[12, 27],
          [61, 74]],

         [[62, 94],
          [27,  9]]]],



       [[[[87, 69],
          [33, 14]],

         [[17, 62],
          [14, 92]]],


        [[[79, 42],
          [ 3, 91]],

         [[31, 34],
          [68, 92]]]]], dtype=int32)>

In [64]:
# tensors can be reshaped

# reshaping a 3-rank tensor into a 2-rank tensor
reshaped_cube = tf.reshape(cube, [3, 9])

# we can also flatten a tensor
flattened_cube = tf.reshape(cube, [-1])

display_table([cube, reshaped_cube, flattened_cube], ['cube', 'reshaped_cube', 'flattened_cube'])

Value  \
cube            [[[87, 89, 61], [86, 92, 84], [83, 43, 71]], [...   
reshaped_cube   [[87, 89, 61, 86, 92, 84, 83, 43, 71], [91, 52...   
flattened_cube  [87, 89, 61, 86, 92, 84, 83, 43, 71, 91, 52, 4...   

                            Type      Shape  Rank  
cube            <dtype: 'int32'>  (3, 3, 3)     3  
reshaped_cube   <dtype: 'int32'>     (3, 9)     2  
flattened_cube  <dtype: 'int32'>       (27)     1

The syntax flattened_cube = tf.reshape(cube, [-1]) is used to reshape a TensorFlow tensor cube into a one-dimensional tensor (i.e., a flattened tensor).

Here's a breakdown of the components:

tf.reshape(tensor, shape): This function reshapes a tensor to the specified shape.
cube: This is the original tensor that you want to reshape.
[-1]: This shape argument tells TensorFlow to flatten the tensor into a one-dimensional tensor. The -1 is a special value in TensorFlow that means "infer the size". When used in the shape, it instructs TensorFlow to calculate the appropriate dimension size to match the total number of elements in the original tensor.